global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fruit_classifier'
    static_configs:
      - targets: ['app:8000', 'app_replica1:8000', 'app_replica2:8000']
    metrics_path: '/metrics'
